name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Make executable
        run: chmod +x android-balllink/gradlew
      - name: Build APK
        run: cd android-balllink &&./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: balllink-apk
          path: android-balllink/app/build/outputs/apk/release/*.apk
